# 自定义配置
mysql:
  ip: 192.168.1.1
  port: 3306
  database: xface
  username: root
  password: 123456
redis:
  ip: 192.168.1.1
  port: 6379
  password: 123456
  database: 1
es:
  ip: 192.168.1.1
  port: 9200
  username: root
  password: 123456

spring:
  application:
    name: xFace
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${mysql.username}
    password: ${mysql.password}
  # Redis 配置
  redis:
    database: ${redis.database}
    host: ${redis.ip}
    port: ${redis.port}
    timeout: 5000
    password: ${redis.password}
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://${es.ip}:${es.port}
  #    username: ${es.username}
  #    password: ${es.password}
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8089
  servlet:
    #    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

mybatis:
  mapperLocations: classpath:mapper/*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    project.test.xface.mapper: debug



# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - ming.test.xface.controller
