# 自定义配置
mysql:
  ip: 192.168.30.128
  port: 3306
  database: xface
  username: root
  password: qwert
redis:
  ip: 192.168.30.128
  port: 6379
  password: qwert
  database: 1
es:
  ip: 192.168.30.128
  port: 9200
  username: root
  password: qwert