# 自定义配置
mysql:
  ip: 127.0.0.1
  port: 3306
  database: xface
  username: root
  password: qwert
redis:
  ip: 127.0.0.1
  port: 6379
  password: qwert
  database: 1
es:
  ip: 127.0.0.1
  port: 9200
  username: root
  password: qwert