---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dell.
--- DateTime: 2024/6/4 10:41
---

local id=redis.call('get',KEYS[1])

if(id == AVRG[1]) then
    return redis.call('del',KEYS[1])
end
return 0